version: '3'
services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_NAME: mysql      
    volumes:
      - dbdata:/var/lib/mysql/      
    networks:
      - app-network    
  api:
    build:
      context: api
      dockerfile: Dockerfile
    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"   
    links:
      - mysql 
    working_dir: /var/www/api
    volumes:
      - ./api:/var/www/api
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    depends_on:
      - mysql  
  app:
    build:
      context: app
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    links:
      - api
    ports:
      - "3000:3000"           
    networks:
      - app-network
    depends_on:
      - api    
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local