version: '3'
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_NAME: mysql      
    volumes:
      - dbdata:/var/lib/mysql/      
    networks:
      - app-network  
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"      
    volumes:
      - ./api/:/var/www/api
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - db
  api:
    build:
      context: api
      dockerfile: Dockerfile
    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"    
    working_dir: /var/www/api
    volumes:
      - ./api:/var/www/api
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    depends_on:
      - db  
  app:
    build:
      context: app
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "3000:3000"           
    networks:
      - app-network
    depends_on:
      - db    
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local